# Generated by Django 5.0.7 on 2024-08-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="accountName",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="accountNumber",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="bank",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="bankCode",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile_images/"
            ),
        ),
    ]
