# Generated by Django 5.0.7 on 2024-08-28 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0002_alter_account_accountname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowdfunding",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="crowdfundingApp.account",
            ),
        ),
    ]
