# Generated by Django 5.0.7 on 2024-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0003_crowdfunding_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowdfunding",
            name="lga",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crowdfunding",
            name="state",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crowdfunding",
            name="amountRaised",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
