# Generated by Django 5.0.7 on 2024-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0004_crowdfunding_lga_crowdfunding_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdfunding",
            name="amountWithdrawn",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="crowdfunding",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/fundraiser/"
            ),
        ),
    ]
