# Generated by Django 5.0.7 on 2024-09-04 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0005_alter_crowdfunding_amountwithdrawn_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crowdfunding",
            name="user",
        ),
        migrations.AddField(
            model_name="crowdfunding",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crowdfundings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
