# Generated by Django 5.1.1 on 2024-10-11 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0008_alter_crowdfunding_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdfunding",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="account",
                to="crowdfundingApp.account",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.TextField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.TextField(max_length=255)),
                ("type", models.TextField(max_length=255)),
                ("serviceStatus", models.TextField(max_length=255, null=True)),
                ("authorizationUrl", models.TextField(max_length=255)),
                ("last4", models.TextField(max_length=255, null=True)),
                ("expMonth", models.TextField(max_length=255, null=True)),
                ("expYear", models.TextField(max_length=255, null=True)),
                ("channel", models.TextField(max_length=255, null=True)),
                ("cardType", models.TextField(max_length=255, null=True)),
                ("bank", models.TextField(max_length=255, null=True)),
                ("countryCode", models.TextField(max_length=255, null=True)),
                ("brand", models.TextField(max_length=255, null=True)),
                ("currency", models.TextField(max_length=255, null=True)),
                ("paidAt", models.TextField(max_length=255, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="campaignTransaction",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transaction",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
