# Generated by Django 5.1.1 on 2024-10-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0009_alter_crowdfunding_account_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="campaignTransaction",
                to="crowdfundingApp.crowdfunding",
            ),
        ),
    ]
