# Generated by Django 5.1.1 on 2024-10-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0012_alter_transaction_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="serviceStatus",
        ),
    ]
