# Generated by Django 5.1.2 on 2024-10-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0013_remove_transaction_servicestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdfunding",
            name="donations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="crowdfunding_donations",
                to="crowdfundingApp.donation",
            ),
        ),
    ]
