# Generated by Django 5.1.2 on 2024-10-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0014_alter_crowdfunding_donations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crowdfunding",
            name="donations",
        ),
    ]
