# Generated by Django 5.1.2 on 2024-10-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdfundingApp", "0019_alter_crowdfunding_amountraised"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crowdfunding",
            name="likes",
        ),
        migrations.AddField(
            model_name="crowdfunding",
            name="likes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
